stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  only:
    - main
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - mkdir -p src/main/resources src/test/resources
    - cp $APP_YAML             ./src/main/resources/application.yaml
    - cp $APP_SECRET_YAML      ./src/main/resources/application-secret.yaml
    - cp $TEST_APPLICATION_YML ./src/test/resources/application.yml
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout $CI_REGISTRY

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 600 $SSH_PRIVATE_KEY
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh -i $SSH_PRIVATE_KEY $SSH_USER@$SERVER_IP "bash /home/ubuntu/app/deploy.sh"
  environment:
    name: production
    url: https://monimentoom.duckdns.org