spring:
  datasource:
    url: jdbc:h2:mem:monimentoom;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: 0808

# JWT 등 커스텀 설정
jwt:
  secret-key: monimentoom-secret-key
  expiration-time: 3600000